---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
  - name: Storage-unit-node
  - name: dependency-cache

run:
  path: Storage-unit-node/ci/scripts/run_tests.sh

